### ISSUE TITLE
Not work with UITableViewController

### ISSUE THREAD

**Issue by andrewSvsg** [FelipeCardoso89/UILoadControl#2]
I added simple TableViewController to sample project for testing and no UILoadControl at the bottom of view

```class TableViewController: UITableViewController {
  override func viewDidLoad() {
    super.viewDidLoad()
    
    let loadControl = UILoadControl()
    loadControl.addTarget(self, action: "loadMore:", forControlEvents: UIControlEvents.ValueChanged)
    tableView.tableFooterView = UIView()
    tableView.loadControl = loadControl
  }
  
  override func didReceiveMemoryWarning() {
    super.didReceiveMemoryWarning()
    // Dispose of any resources that can be recreated.
  }
  
  @objc private func loadMore(sender: AnyObject?) {
    let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(4 * Double(NSEC_PER_SEC)))
    dispatch_after(delayTime, dispatch_get_main_queue()) {
      self.tableView.loadControl?.endLoading()
    }
  }
}```

**Comment by nelsongc** [comment]
same problem, have you found solution?
UILoadControl_UIScrollView.swift

extension UIScrollView {
  
  /*
  Place UILoadControl if its not in the scrollView
  */
  private func showRefreshControlBottomIfNeeded(){
    
    guard let loadControl = self.loadControl else {
      return
    }

**    self.delegate = self**
    loadControl.scrollView = self
    
    if self.loadControlView == nil {
      let loadControlView = UIView()
      loadControlView.clipsToBounds = true
      loadControlView.addSubview(loadControl)
      addSubview(loadControlView)
      self.loadControlView = loadControlView
    }
  }
}

the instruction self.delegate = self
overwrite the tableView.delegate

**Comment by felipecardoso-luizalabs** [comment]
I´m working to solve this problems. I will update it soon.

**Comment by FelipeCardoso89** [comment]
Hello again. 

I've been trying to solve the problem about the delegate override but I can't find an alternative to observe the scroll of scrollview. I tried to use KVO but i need to remove the KVO observer after scroll view is deallocated and there is no way to access the `deinit{ }` method from the scrollview extension.

I'm thinking about to use RxSwift to observe the `contentOffSet` scrollView property, by this way I can remove de scrollViewDidScroll method from UILoadControl lib.

I agree RxSwift is overload. 

Let me know if you guys have some suggestion.

**Comment by nelsongc** [comment]
I have some modification just for working with your great library.

1: UILoadControl_UIScrollView.swift   --- comment delegate instruction
    extension UIScrollView {
  
  /*
  Place UILoadControl if its not in the scrollView
  */
  private func showRefreshControlBottomIfNeeded(){
    
    guard let loadControl = self.loadControl else {
      return
    }
    
    //self.delegate = self
    loadControl.scrollView = self
    
    if self.loadControlView == nil {
      let loadControlView = UIView()
      loadControlView.clipsToBounds = true
      loadControlView.addSubview(loadControl)
      addSubview(loadControlView)
      self.loadControlView = loadControlView
    }
  }
}
2: UILoadControl.swift change the function updateUI() to access from my Controller
from 
func updateUI(){...}
to
public func updateUI(){...}
   
3: the only function of UIScrollViewDelegate is scrollViewDidScroll, but all function about UIScrollViewDelegate is included in UITableView so in my class EmpresasController.swift add 
func scrollViewDidScroll(scrollView: UIScrollView) {
        guard let loadControl = scrollView.loadControl else {
            return
        }
        
        loadControl.updateUI()
    }
   
I hope have helped in something

**Comment by FelipeCardoso89** [comment]
I think this is the best solution for now @nelsongc

I will update this lib with some refactoring code and I will add your suggestion into it.
It will be 2.0.0 in the next release.

Thank you. :)

**Comment by FelipeCardoso89** [comment]
Fixed. Thank you @nelsongc. :)
